-- Enable Row Level Security on all tables
ALTER TABLE "Game" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GameTurn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BoardState" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Battle" ENABLE ROW LEVEL SECURITY;
